### PR TITLE
Fix #156

### LINKED ISSUE #156: "No API definition provided." when using `swagger-config-file`
When providing a `swagger-config-file` (for example `swagger-config.yaml`), it's [copied as a `swagger-config` file (without an extension)](https://github.com/Legion2/swagger-ui-action/blob/54a47226bac6644fa6ec55119badff9dcf67e831/src/swagger-ui-action.ts#L66). This file is then [used by `SwaggerUIBundle` in `index.html`](https://github.com/MonkiProjects/mp-api-specs/blob/6793197a395d39bda94bd7c38c95643987be1010/index.html):

```js
// Begin Swagger UI call region
const ui = SwaggerUIBundle({
    configUrl: "swagger-config",
    dom_id: '#swagger-ui'
})
// End Swagger UI call region
```

(I think) the problem is that when Swagger UI reads the configuration file, it doesn't know what format it's written in (see [the documentation about Swagger UI parameters](https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/#core). The resulting Swagger UI is a blank page with "No API definition provided.".

A solution would be to use

```js
const swaggerConfigFileName = basename(config.swaggerConfigFile);
io.cp(
    config.swaggerConfigFile,
    join(config.outputPath, swaggerConfigFileName)
);
return swaggerConfigFileName;
```

instead of

```js
io.cp(
    config.swaggerConfigFile,
    join(config.outputPath, 'swagger-config')
);
return 'swagger-config';
```

in [swagger-ui-action.ts#L66](https://github.com/Legion2/swagger-ui-action/blob/54a47226bac6644fa6ec55119badff9dcf67e831/src/swagger-ui-action.ts#L66).

### PR DESCRIPTION
**Pull request by RemiBardon**
Fixes #156.

### CODE REVIEW

**Comment by Legion2** [comment]
can you add a test please

**Comment by RemiBardon** [comment]
I'm adding a test. You had forgotten an `await` statement before an `io.cp`: [src/swagger-ui-action.ts#L66](https://github.com/Legion2/swagger-ui-action/blob/0c413a52b033c87de664a459d766c95b96c6a123/src/swagger-ui-action.ts#L66).

**Comment by RemiBardon** [comment]
I added a test ✅

**Review by Legion2 — APPROVED** [review]
Thanks

**Pull request merged**
